# Netlify Configuration for Dashboard MORA (Pure Web Base)

[[redirects]]
  from = "/api/sheets/summary"
  to = "https://docs.google.com/spreadsheets/d/1wQV3dYvMY5XaJNkw7y-4ZycZ8VmJcScQPRTFp1wSvnY/export?format=csv&gid=1112038042"
  status = 200
  force = true

[[redirects]]
  from = "/api/sheets/transfer"
  to = "https://docs.google.com/spreadsheets/d/1wQV3dYvMY5XaJNkw7y-4ZycZ8VmJcScQPRTFp1wSvnY/export?format=csv&gid=747143276"
  status = 200
  force = true
